### ISSUE TITLE
Idea: be able to specify helper functions from yaml

### ISSUE THREAD

**Issue by llamicron** [llamicron/lab_grader#11]
maybe have a `prebuilt` field or something in the yaml spec of a criterion that calls a helper function. Example

```yaml
criteria:
  My Criterion:
    # ...
    prebuilt:
      command: file_exists
      args: "path/to/file"
```

This seems like it could work with any command that takes string/number arguments. Might get hairy on parsing what command to use. Possibly an enum with each help function? Would need to add an enum listing for every new helper function. Just a thought
